### ISSUE TITLE
Getting error when trying to get docusign using composer

### ISSUE THREAD

**Issue by varun1607** [Tucker-Eric/Laravel-Docusign#1]
Hi Eric,

I am trying to download docusign using composer and I am running this command
composer require tucker-eric/laravel-docusign

But I am always getting an error.
tucker-eric/laravel-docusign 0.1.0 requires tucker-eric/docusign-rest-client dev-master -> no matching package found.

Please tell me how can I be able to download it via composer.

Thanks,
Varun

**Comment by Tucker-Eric** [comment]
I updated the composer dependencies so that command will work now. If it doesn't then run `composer clear-cache` and run it again.

**Comment by varun1607** [comment]
Hi Eric,

Still getting the same error, even after clearing cache.

Problem 1
    - Installation request for tucker-eric/laravel-docusign ^0.1.0 -> satisfiable by tucker-eric/laravel-docusign[0.1.0].
    - tucker-eric/laravel-docusign 0.1.0 requires tucker-eric/docusign-rest-client dev-master -> no matching package found.

**Comment by Tucker-Eric** [comment]
Add the following to your `composer.json`

```
"tucker-eric/laravel-docusign": "^0.1.1"
```

Then run `composer install`

**Comment by varun1607** [comment]
Still getting error. Below is the error mentioned.

The requested package tucker-eric/laravel-docusign could not be found in any version, there may be a typo in the package name.

**Comment by Tucker-Eric** [comment]
Just recreated on my end and able to install. Revert your `composer.json` from what I had previously advised and then run `composer require tucker-eric/laravel-docusign`
