### ISSUE TITLE
DocuSignClient overrides Laravel config parameters

### ISSUE THREAD

**Issue by strotgen** [Tucker-Eric/Laravel-Docusign#13]
Hi again!

I am having the following issue: 

When using `DocuSign::create()` or `new LaravelDocusign\Client`, it takes the config parameters from my .env file correctly, but then they get overridden at the `DocuSign\Rest\Client` constructor. Is this the expected behaviour or I am missing something? If not, I could create a PR for this issue. 

I know I could manually pass the $params array and that would solve the issue, but I think it is more convenient if this is done behind the scenes and only give the option to override this if needed.

**Comment by Tucker-Eric** [comment]
Oh! You're right! This was an oversight! There were some changes made to https://github.com/Tucker-Eric/docusign-rest-client but nothing reflected in this package. 

Yes, a PR to fix would be much appreciated!
