### ISSUE TITLE
Signature field not adding to each singer

### ISSUE THREAD

**Issue by vivek-negi** [Tucker-Eric/Laravel-Docusign#16]
I am using template_id inside definition wrapper, I have already created fields on DocuSign portal and wanted to fill data into those fields and wanted to collected signature for each, but signature fields only showing to default user that I added in template from UI, if I am adding more signers from code then signature not showing them, can you please help me ?

**Comment by Tucker-Eric** [comment]
Can you share your code?

**Comment by vivek-negi** [comment]
[filecode.txt](https://github.com/Tucker-Eric/Laravel-Docusign/files/5162806/filecode.txt)

Here is my code I also tried to add this tag but no luck
`$tabs['checkboxTabs'] = [
 
]`

**Comment by Tucker-Eric** [comment]
This looks Docusign API specific in your template. Everything there looks fine to me.

**Comment by vivek-negi** [comment]
Docusign API specific means? how to make it for all any idea?

**Comment by Tucker-Eric** [comment]
I don't believe your issue is due to this package so you'd have to open an issue https://github.com/docusign/docusign-php-client which is the underlying package that this one uses to interact with DocuSign
