### ISSUE TITLE
Need Help : Creating custom template programmatically 

### ISSUE THREAD

**Issue by AEK-BKF** [Tucker-Eric/Laravel-Docusign#19]
Hello,

Thanks for this package,
Please I have some questions:
1- How can I create a document programmatically where I fill some data from database, and then I send it to signers?
2- How can I check if any signer has signed his part ?
3- How can I check if it's signed or cancelled ? 
4- How can I upload the document after has been signed ?
 
Thanks.

**Comment by Tucker-Eric** [comment]
This package adds some ease of access to the official docusign library (https://github.com/docusign/docusign-php-client). You should be able to find the answers to your questions there or in the link from that repo to their developer center.
