### ISSUE TITLE
Error: "API call to /v2/login_information failed: <url> malformed"

### ISSUE THREAD

**Issue by ShawnCorrigan** [Tucker-Eric/Laravel-Docusign#2]
The library seems to be calling the URL /v2/login_information.

I am getting the error 
`
API call to /v2/login_information failed: <url> malformed
`

The only thing that I am using with it is..

`
DocuSign::get('envelopes')->list();
`
I set the environment variables

```
DOCUSIGN_USERNAME=
DOCUSIGN_PASSWORD=
DOCUSIGN_INTEGRATOR_KEY=
```

I can't really provide much more information since I'm really not trying to do much to it.

I see in the original Tucker-Eric/docusign-rest-client you are supposed to set the host, but I don't see any option for that with this one. Is there a place to do that here? How do I make it call the right URL?

**Comment by Tucker-Eric** [comment]
Did you publish and update the config?
```bash
php artisan vendor:publish --provider="LaravelDocusign\DocusignServiceProvider"
```

**Comment by ShawnCorrigan** [comment]
I thought I had done that but now config file is showing up so I must have been doing something wrong. Now I am getting a 401 error. Is there anything else that I should be doing to authenticate? I have dumped the username, password, and integrator key and they all seem to be cached correctly. This is also happening if I use the docusign/docusign-php-client package so I may just be doing something wrong.

This should use Legacy Header Authentication, right? Do I need to set up a secret key, redirect URL, RSA pair, or anything along those lines to get authentication to work?

**Comment by ShawnCorrigan** [comment]
I was able to trace the 401 to an invalid username and password. I thought that the username was the API username but it was actually the email. The password is my actual login password.

**Comment by Tucker-Eric** [comment]
Ahh, that'll do it every time. Glad we could figure it out!
