### ISSUE TITLE
Class 'DocuSign/eSign' not found after installing with Composer 2

### ISSUE THREAD

**Issue by tcov189** [Tucker-Eric/Laravel-Docusign#20]
After upgrading to Composer 2, we get the following error when trying to use facade:
`PHP Fatal error:  Class 'DocuSign/eSign/Api/EnvelopesApi/GetEnvelopeOptions' not found`

Reverting back to Composer 1 fixes the issue.

This is replicated by doing the following
1. Purge `vendor` directory
2. `composer self-update --2`
3. `composer install`
4. `php artisan tinker`
5. `new \DocuSign\eSign\Api\EnvelopesApi\GetEnvelopeOptions`
6. Error shows

**Comment by Tucker-Eric** [comment]
It looks like this is an issue with https://github.com/docusign/docusign-php-client

**Comment by tcov189** [comment]
Ok, I will submit an issue there. Thanks
