### ISSUE TITLE
Class 'DocuSign\eSign\client\ApiClient' not found

### ISSUE THREAD

**Issue by lovelight24** [Tucker-Eric/Laravel-Docusign#24]
Hello Mr. Tucker,

I am used "tucker-eric/laravel-docusign": "4.1.0" in laravel 8.0. Getting error on click finish on Docusign after signed.

**Comment by Tucker-Eric** [comment]
Without knowing more than provided, it looks like your namespace is incorrect. `Client` should be capitalized. The full namespace should be `DocuSign\eSign\Client\ApiClient`

**Comment by lovelight24** [comment]
Thanks Mr. Tucker,

Issue Resolved.
