### ISSUE TITLE
Refuse to display because it set X-Frrame-Option Deny in Chrome 91.0 version

### ISSUE THREAD

**Issue by lovelight24** [Tucker-Eric/Laravel-Docusign#26]
After Successfully signed the document, when we redirect to our website, It shows an error page on google chrome's latest version 91.0. 
Error: Refuse to display http://www.xxxxx.com in a frame because it set  X-Frame-Option to Deny.

**Comment by Tucker-Eric** [comment]
Sounds like that issue is the same as this one https://stackoverflow.com/a/59971122/5600657 ?
