### ISSUE TITLE
class 'DocuSign\eSign\Api\FoldersApi' does not have a method 'list'

### ISSUE THREAD

**Issue by andcl** [Tucker-Eric/Laravel-Docusign#4]
Very strange behaviour: I can not make the package work within Laravel 5.8.
Everything is installed as per docs, and API calls are executed (as if I change the credentials within `.env` file, I get an authentication error...). But when I execute this code (within `routes/web.php`):

```
Route::get('docusign', function (){
    $client = \LaravelDocusign\Facades\DocuSign::create();
    dd($client->folders->list());
});
```
...I get the following Laravel error:
```
call_user_func_array() expects parameter 1 to be a valid callback, class 'DocuSign\eSign\Api\FoldersApi' does not have a method 'list'
```
Of course, Folders API v2.0 and 2.1 do have a list method.
Do you have any ideas of what is causing that?

Thanks in advance.

**Comment by andcl** [comment]
However, executing `$client->folders->callList()` instead of `$client->folders->list()` does the trick.
Is there an error in the package then?

Thanks.

**Comment by Tucker-Eric** [comment]
Looks like `list` was renamed to `callList` [here](https://github.com/docusign/docusign-php-client/commit/ccc86ac37334f34728361d73b2f8c4592225b8d2#diff-8a141e5d63ecc2bde59bf7ac235352ffR638).

`callList` should be the correct method as this library is a very thin wrapper around the [official package](https://github.com/docusign/docusign-php-client) to provide easier class resolution and stored authentication. Other than that, all calls are forwarded to the official package.
